- name: Create an ec2 instance
  ec2:
    key_name: "aws-demo-rh75"
    aws_access_key: "{{ my_access_key }}"
    aws_secret_key: "{{ my_secret_key }}"
    group: launch-wizard-1  # security group name
    instance_type: "t2.micro"
    image: "ami-0a74bfeb190bd404f"
    wait: true
    region: "ap-south-1"
    count: 1  # default
    count_tag:
      Name: "aws-rh8-03"
    instance_tags:
      Name: "aws-rh8-03"
    vpc_subnet_id: "subnet-3db5ec55"
    assign_public_ip: yes
  register: ec2
    
- debug:
    msg: "{{ item['private_ip'] }}"
  with_items: "{{ ec2.instances }}"

- name: Add all web instance IPs to host group
  add_host: 
    hostname: "{{ item.private_ip }}"
    groupname: webservers
    ansible_user: ec2-user 
  with_items: '{{ ec2.instances }}'

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: '{{ ec2.instances }}'
