---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.micro
      ami: ami-0a74bfeb190bd404f  # Redhat
      keypair: aws-demo-rh75 # pem file name

  tasks:
    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: "{{ my_access_key }}"
         aws_secret_key: "{{ my_secret_key }}"
         group: launch-wizard-1  # security group name
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: "aws-rh8-03"
         instance_tags:
            Name: "aws-rh8-03"
         vpc_subnet_id: "subnet-3db5ec55"
         assign_public_ip: yes
      register: ec2
    - name: check data for task
      debug: var=ec2
